### ISSUE TITLE
Use with Next.js documentation

### ISSUE THREAD

**Issue by mrcnk** [insites-co/insites-ui#8]
We don't have the doc about how to use the framework with Next.js. I'd be grateful if anyone can help to sort it out.

https://insites-ui-docs.netlify.app/framework-specific/next/

Docs repo: https://github.com/insites-co/insites-ui-docs/blob/master/content/framework-specific/next.mdx

As far as I know, there's a problem with Styled Components and Next. When @rago4 tried to add insites-ui to Next, there was an error that className did not match.
https://github.com/zeit/next.js/issues/7322

**Comment by rago4** [comment]
I've managed to resolve this issue by adding `styled-components` and `insites-ui` to the `withTM` plugin like this:
```
// /next.config.js
const withTM = require('next-transpile-modules')([
  'styled-components',
  'insites-ui',
]);
```
You can find more details in the following [PR](https://github.com/insites-co/insites-ui-docs/pull/2).

**Comment by mrcnk** [comment]
Nice one. Thanks 🤙

**Comment by zerofront** [comment]
@rago4 
Can you explain why adding this configuration can solve the  problem zeit/next.js#7322?

**Comment by rago4** [comment]
@zerofront
TBH I'm not really sure 😅
Since `next` doesn't transpile modules from `node_modules` (https://github.com/zeit/next.js/issues/706) we had to use `next-transpile-modules` to integrate `insites-ui` with `next`. At first configuration looked like this👇
```js
const withTM = require('next-transpile-modules')(['insites-ui']);
```
After hours of searching for solution I found an information that the issue might be caused by `babel`. So I've decided to give it a try and put `styled-components` to the `withTM` plugin since this might use some other `babel` version to transpile packages, and violla - it worked 🎉
